### ISSUE TITLE
Error: BucketAlreadyExists: The requested bucket name is not available.

### ISSUE THREAD

**Issue by n0kovo** [DevSecOpsDocs/terraform-nuclear-pond#1]
Getting the following error after setting up ```awscli```, configuring credentials, cloning this repo and running ```terraform apply```

<img src='https://user-images.githubusercontent.com/16690056/210587836-e8dc129d-08cd-4f9f-8690-60a67d22f3b7.png' height=200 >

**Comment by jonathanwalker** [comment]
Apologies for missing this! You need to update the project variable name as S3 bucket names are global. Let me know if you need any help!

**Comment by jonathanwalker** [comment]
Thanks again for submitting the issue! 

I have updated the module variables to help avoid this confusion and please do not hesitate to open more issues if you run into them.
